-- College Bus Connect - Supabase PostgreSQL schema
-- Run this entire file in Supabase Dashboard -> SQL Editor -> New query.
-- Demo password for seeded users: 1234. Change before public launch.

DROP TABLE IF EXISTS stop_runs, route_runs, daily_status, students, drivers, bus_stops, buses, routes, users CASCADE;

CREATE TABLE users(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_code VARCHAR(50) UNIQUE NOT NULL,
 name VARCHAR(120) NOT NULL,
 password_hash VARCHAR(255) NOT NULL,
 role VARCHAR(20) NOT NULL CHECK (role IN ('student','driver','admin')),
 active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE routes(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 route_name VARCHAR(120) UNIQUE NOT NULL
);

CREATE TABLE buses(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bus_number VARCHAR(50) UNIQUE NOT NULL,
 route_id BIGINT NOT NULL REFERENCES routes(id),
 active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE bus_stops(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 route_id BIGINT NOT NULL REFERENCES routes(id),
 stop_order INT NOT NULL,
 stop_name VARCHAR(120) NOT NULL,
 expected_time TIME NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE students(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT UNIQUE NOT NULL REFERENCES users(id),
 bus_id BIGINT NOT NULL REFERENCES buses(id),
 stop_id BIGINT NOT NULL REFERENCES bus_stops(id)
);

CREATE TABLE drivers(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT UNIQUE NOT NULL REFERENCES users(id),
 bus_id BIGINT NOT NULL REFERENCES buses(id),
 active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE daily_status(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
 status_date DATE NOT NULL,
 travel_status VARCHAR(20) NOT NULL DEFAULT 'not_confirmed' CHECK (travel_status IN ('not_confirmed','going','not_going')),
 stop_status VARCHAR(20) NOT NULL DEFAULT 'not_marked' CHECK (stop_status IN ('not_marked','at_stop','coming')),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(student_id,status_date)
);

CREATE TABLE route_runs(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 driver_id BIGINT NOT NULL REFERENCES drivers(id),
 run_date DATE NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'started' CHECK (status IN ('started','completed','cancelled')),
 started_at TIMESTAMPTZ,
 UNIQUE(driver_id,run_date)
);

CREATE TABLE stop_runs(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 driver_id BIGINT NOT NULL REFERENCES drivers(id),
 stop_id BIGINT NOT NULL REFERENCES bus_stops(id),
 run_date DATE NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'completed' CHECK (status='completed'),
 completed_at TIMESTAMPTZ,
 UNIQUE(driver_id,stop_id,run_date)
);

INSERT INTO routes(route_name) VALUES('Bus 163 Route');
INSERT INTO buses(bus_number,route_id) VALUES('163',1);
INSERT INTO bus_stops(route_id,stop_order,stop_name,expected_time) VALUES
(1,1,'High School','08:00:00'),
(1,2,'CSI Church','08:10:00'),
(1,3,'PCB','08:20:00'),
(1,4,'Palayakottai Road','08:30:00'),
(1,5,'Vaikalmedu','08:40:00'),
(1,6,'Nathakadaiyur','08:50:00'),
(1,7,'Komarapalayam','09:00:00');

INSERT INTO users(user_code,name,password_hash,role) VALUES
('YOGESH','Yogesh','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','admin'),
('TAMIL','Tamil','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','driver');

INSERT INTO drivers(user_id,bus_id) SELECT id,1 FROM users WHERE user_code='TAMIL';

INSERT INTO users(user_code,name,password_hash,role) VALUES
('STU001','Yogesh','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU002','Praveen','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU003','Manikandan','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU004','Kalai','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU005','Sathish','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU006','Bhawan','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU007','Sibi','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU008','Abi','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU009','Santhosh','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU010','Aathi','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU011','Sudhan','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU012','Girl','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU013','Harish','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student'),
('STU014','Maha','$2b$12$LQv3c1yqBW1A1gYpVx7ZNeQ3b5e5sYkqHq4ZJtL0c3Jv9r2w5n7mK','student');

INSERT INTO students(user_id,bus_id,stop_id)
SELECT u.id,1,bs.id FROM users u CROSS JOIN bus_stops bs
WHERE u.role='student' AND (
 (u.user_code IN ('STU001','STU002','STU003','STU004') AND bs.stop_order=1) OR
 (u.user_code IN ('STU005','STU006','STU007','STU008','STU009','STU010') AND bs.stop_order=3) OR
 (u.user_code='STU011' AND bs.stop_order=4) OR
 (u.user_code='STU012' AND bs.stop_order=5) OR
 (u.user_code IN ('STU013','STU014') AND bs.stop_order=6)
);
